spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"  # Use isto ao invés de allowedOrigins
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:3000}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8080}
          predicates:
            - Path=/api/orders/**
          filters:
          #  - name: JwtAuthFilter // TO-DO: Turn on the filter
            - StripPrefix=1

        - id: tracking-service
          uri: ${TRACKING_SERVICE_URL:http://tracking-service:8081}
          predicates:
            - Path=/api/tracking/**
          filters:
          #  - name: JwtAuthFilter  // TO-DO: Turn on the filter 
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET:ml2V8C#p9qK3&nX5^zA7@wR4tY6*hJ}  # Deve ser o mesmo secret usado no auth-service

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.security]': DEBUG
    '[com.example.gateway]': DEBUG
    '[reactor.netty]': DEBUG
