spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "Authorization,Content-Type"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:3000}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8080}
          predicates:
            - Path=/api/orders/**
          filters:
            # - name: AuthenticationFilter
            - StripPrefix=1

        - id: tracking-service
          uri: ${TRACKING_SERVICE_URL:http://tracking-service:8081}
          predicates:
            - Path=/api/tracking/**
          filters:
            # - name: AuthenticationFilter
            - StripPrefix=1
